[package]
name = "rustup-available-packages"
version = "0.2.1"
authors = ["mexus <gilaldpellaeon@gmail.com>"]
description = "Rustup tools state info"
license = "MIT/Apache-2.0"
keywords = ["rustup"]
repository = "https://gitlab.com/mexus/rustup-components-availability"
documentation = "https://docs.rs/rustup-available-packages/"
readme = "README.md"
edition = "2018"

[dependencies]
chrono = { version = "0.4.6", features = [ "serde" ] }
derive_more = "0.14.0"
thiserror = "1"
log = "0.4.5"
reqwest = { version = "0.10.0", features = ["blocking"] }
serde = { version = "1", features = [ "derive" ] }
toml = "0.5"
