name: Rust

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 01:10,02:10,03:10 UTC every day.
    # Random minutes are used because:
    # https://github.com/rust-lang/rustup-components-history/pull/38#discussion_r667472423
    - cron: '10 1,2,3 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare pages
      run: ./prepare-pages.sh
    - name: Deploy GitHub Pages
      run: |
        git worktree add gh-pages gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../output/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force
