name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 2:00 UTC every day (to give the release process 2h to complete).
    - cron: '0 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare pages
      run: ./prepare-pages.sh

    - name: Deploy GitHub Pages
      # Do not deploy PRs.
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git worktree add gh-pages gh-pages
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../output/* .
        git add .
        git -c 'user.name=github-actions[bot]' -c 'user.email=41898282+github-actions[bot]@users.noreply.github.com' \
          commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force
